### ISSUE TITLE
`is_function` does not accept `functools.partial`

### ISSUE THREAD

**Issue by wcooley** [jealous/retryz#1]
Version 0.1.8,
Python: Python 3.5 & 3.3; Legacy 2.7

The predicate `retryz.retry.is_function` does not accept a `functools.partial` as a callable, so it is not possible to use a partial function as value for parameters `on_return`, `on_error`, `on_retry`, etc. (Wrapping the partial with a `lambda` works fine, though.)

**Comment by jealous** [comment]
Thanks for reporting the issue.  Let me see what I can do.

**Comment by jealous** [comment]
Fixed in 0.1.9.
